name: CI-Harbor

on:
  push:
    branches:
      - master  # 또는 배포할 브랜치

jobs:
  build-and-push:
    runs-on: self-hosted  # Self-hosted runner 사용
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'


      - name: Login to Harbor
        run: |
          docker login https://192.168.2.76:443 -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}


      - name: Build and push Docker images
        run: |
          docker build -t 192.168.2.76:443/hama/hama-product:latest .
          docker push 192.168.2.76:443/hama/hama-product:latest
